#!/bin/bash

sbatch ablation_scripts/run_value_reward_ablations_close.sh "$@"
sbatch ablation_scripts/run_value_reward_ablations_far.sh "$@"
sbatch ablation_scripts/run_value_reward_ablations_mid.sh "$@"
sbatch ablation_scripts/run_value_reward_ablations.sh "$@"
sbatch ablation_scripts/run_value_ablations_mid.sh "$@"
sbatch ablation_scripts/run_value_ablations_far.sh "$@"
sbatch ablation_scripts/run_value_ablations.sh "$@"
sbatch ablation_scripts/run_value_ablations_close.sh "$@"
sbatch ablation_scripts/run_reward_ablations_close.sh "$@"
sbatch ablation_scripts/run_reward_ablations_mid.sh "$@"
sbatch ablation_scripts/run_reward_ablations_far.sh "$@"
sbatch ablation_scripts/run_reward_ablations.sh "$@"
sbatch ablation_scripts/run_policy_ablations_mid.sh "$@"
sbatch ablation_scripts/run_policy_ablations.sh "$@"
sbatch ablation_scripts/run_policy_ablations_close.sh "$@"
sbatch ablation_scripts/run_policy_ablations_far.sh "$@"
sbatch ablation_scripts/run_no_ablations_close.sh "$@"
sbatch ablation_scripts/run_no_ablations_far.sh "$@"
sbatch ablation_scripts/run_no_ablations_mid.sh "$@"
sbatch ablation_scripts/run_no_ablations.sh "$@"